### PR TITLE
korean localization

### PR DESCRIPTION
**Pull request by Gullwing-door**
korean loc: https://drive.google.com/file/d/127j47BaV7LNe7zGn7mwhOg5wdgwGqoa_/view?usp=sharing

need inspection, don't include killfeed, because other languages seem to do the same. only include coreloc, locko
also Restoration HUD has no problems, but some fonts are missing.

### CODE REVIEW

**Comment by Gullwing-door** [comment]
link: https://drive.google.com/file/d/1fpGgnHUDBJfUk85LJPGjbr5nyZL9BQHu/view?usp=sharing

Some minor typos or some parts corrected and untranslated parts translated

**Comment by Gullwing-door** [comment]
link: https://drive.google.com/file/d/1fpGgnHUDBJfUk85LJPGjbr5nyZL9BQHu/view?usp=sharing

oof, Resolves an issue where biker peck deck descriptions were not colored.

**Comment by Gullwing-door** [comment]
link: https://drive.google.com/file/d/1fpGgnHUDBJfUk85LJPGjbr5nyZL9BQHu/view?usp=sharing

Fixed some mistranslations, typos and expressions

**Comment by Gullwing-door** [comment]
link: https://drive.google.com/file/d/1fpGgnHUDBJfUk85LJPGjbr5nyZL9BQHu/view?usp=sharing

Fixed a part of the Crime Spree modifier and a part where the name of the Titan Sniper was not changed

**Comment by EssCee** [comment]
Added with commit 13effd32bae764b98ca7b32e4016567c8ba63583

**Pull request closed without merging**
