### PR TITLE
spread pattern fix

### PR DESCRIPTION
**Pull request by Skwuruhl**
The vanilla spread system distributes shots in a cross shape. This fixes spread to distribute as one would expect spread to work. The actual size of the cone of where your bullets go doesn't change, it's just circle shaped (or oval with duckbill) instead of + shaped.

tweak_data.weapon.spread.dispersion is defaulted to 1.0 which distributes shots evenly by radius. However by area shots will be weighted towards the middle of your spread, if you want spread to distribute evenly by area change this value to 0.5. Just note this will have the opposite effect and shots will be weighted to the outside of your spread radius.

Personally I think 1.0 is the better value as the radius of spread is what makes your shot hit or miss but it is visually weighted to the center.

### CODE REVIEW

**Comment by sonj2** [comment]
Hey, so for the changes in shotgun base lua, is that just for the shotgun spread? I wanted to know since its very close to what IrenFist has for its shotgun mechanic except for pellet prioritization and keeping track of pellet count, which are only 23 additional lines that would be in the hit_enemy function. Pixy said it's fine to use the shotgun code in that mod, so it wouldn't be a problem even if it was identical.

**Comment by Skwuruhl** [comment]
So the "base" of the _fire_raycast functions are just from the [decompiled payday 2 lua](https://github.com/mwSora/payday-2-luajit/blob/master/pd2-lua/lib/units/weapons/shotgun/shotgunbase.lua). The only lines I actually change from that are the same ones I changed in newflamethrowerbase.lua. [I wrote this code myself](https://github.com/Skwuruhl/pd2-spread-fix). Most of the work was figuring out exactly how the vanilla method worked and then knowing the math of how to implement normal spread patterns.

**Comment by sonj2** [comment]
So that is where the similar lines came from. Keep on the great work then.

**Comment by EvilBobarino** [comment]
will take a look at this for 9.7 (or whatever we call it)

**Pull request merged**
